import AsyncStorage from "@react-native-async-storage/async-storage";
import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const TERMS_VIEWED_KEY = "termsViewed";

export default function TermsScreen() {
  const handleAcknowledge = async () => {
    try {
      await AsyncStorage.setItem(TERMS_VIEWED_KEY, "true");
      router.back();
    } catch (error) {
      console.error("Failed to save terms acknowledgment:", error);
      router.back();
    }
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <View style={styles.container}>
        <ScrollView
          contentContainerStyle={styles.content}
          showsVerticalScrollIndicator={false}
        >
          <Text style={styles.title}>Terms & Privacy Policy</Text>
          <Text style={styles.updated}>Last Updated: March 30, 2026</Text>

          <Text style={styles.sectionTitle}>1. Important Disclaimer</Text>
          <Text style={styles.body}>
            Selfie Dental Assistant is a non-diagnostic screening and educational
            application developed as a capstone project. It does not provide a
            medical or dental diagnosis and does not replace a licensed dentist,
            physician, or other healthcare professional. Any results, scores, risk
            indicators, or recommendations generated by the application are for
            informational purposes only.
          </Text>

          <Text style={styles.sectionTitle}>2. Consent to Use</Text>
          <Text style={styles.body}>
            By creating an account and using this application, you acknowledge that
            you have read these Terms and Privacy Policy and agree to the collection,
            use, storage, and handling of your information as described below.
          </Text>

          <Text style={styles.sectionTitle}>3. Data We May Collect</Text>
          <Text style={styles.body}>
            We may collect account details such as username and email address,
            questionnaire responses, uploaded oral photographs, scan results,
            device/app usage data, and technical logs needed to support application
            performance, safety, and troubleshooting.
          </Text>

          <Text style={styles.sectionTitle}>4. Personal Health Data</Text>
          <Text style={styles.body}>
            Some information processed by this app may relate to your oral health,
            symptoms, habits, or photographic images of your teeth and mouth. This
            information may be considered sensitive personal information or personal
            health information depending on the jurisdiction. We treat this category
            of information with increased care and limit its use to the core app
            functions, safety monitoring, research validation, and authorized project
            evaluation.
          </Text>

          <Text style={styles.sectionTitle}>5. Why We Collect Data</Text>
          <Text style={styles.body}>
            Data is collected to create and manage user accounts, perform image and
            questionnaire-based risk assessments, improve system reliability,
            validate prototype performance, support academic review of the capstone
            project, and maintain security and auditability of the system.
          </Text>

          <Text style={styles.sectionTitle}>6. Privacy and Security</Text>
          <Text style={styles.body}>
            We aim to follow privacy-by-design and minimum-necessary-data principles.
            Reasonable safeguards may include secured transmission, restricted access,
            protected storage, and limiting data exposure to authorized team members
            or supervisors only. No security system can guarantee absolute protection,
            but we seek to reduce unauthorized access risks wherever practical.
          </Text>

          <Text style={styles.sectionTitle}>7. Data Sharing</Text>
          <Text style={styles.body}>
            We do not sell personal information. Data may only be shared with
            authorized academic supervisors, evaluators, or technical team members
            who require access for project operation, review, or compliance. Where
            possible, de-identified or aggregated information should be used instead
            of directly identifiable data.
          </Text>

          <Text style={styles.sectionTitle}>8. Data Retention</Text>
          <Text style={styles.body}>
            Information should only be retained for as long as reasonably necessary
            to support the capstone project, evaluation, troubleshooting, security,
            or legal/academic obligations. When no longer needed, data should be
            deleted, anonymized, or securely disposed of where feasible.
          </Text>

          <Text style={styles.sectionTitle}>9. User Responsibilities</Text>
          <Text style={styles.body}>
            You agree to provide truthful information, upload only images that you
            are authorized to provide, and use the application only for lawful and
            appropriate purposes. You should not rely on this app as a substitute for
            professional dental care.
          </Text>

          <Text style={styles.sectionTitle}>10. Limitation of Liability</Text>
          <Text style={styles.body}>
            This application is provided on an “as is” and “as available” basis for
            educational and prototype purposes. The project team is not responsible
            for medical decisions, missed diagnoses, treatment delays, or any loss
            arising from reliance on the app’s outputs.
          </Text>

          <Text style={styles.sectionTitle}>11. Your Acknowledgment</Text>
          <Text style={styles.body}>
            By proceeding, you acknowledge that you have reviewed this policy and
            understand that the app may process personal and health-related data as
            part of its functionality.
          </Text>
        </ScrollView>

        <TouchableOpacity style={styles.button} onPress={handleAcknowledge}>
          <Text style={styles.buttonText}>I Have Read This</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F8FAFF",
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 16,
  },
  content: {
    paddingBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 8,
  },
  updated: {
    fontSize: 13,
    color: "#64748B",
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#0F172A",
    marginTop: 14,
    marginBottom: 8,
  },
  body: {
    fontSize: 14,
    lineHeight: 22,
    color: "#334155",
  },
  button: {
    backgroundColor: "#1E6FD9",
    borderRadius: 999,
    paddingVertical: 15,
    alignItems: "center",
    marginTop: 12,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
  },
});